### PR TITLE
Role Mapping

### PR DESCRIPTION
**Pull request by craigatproperly**
This doc maps "typical" five level industry job descriptions to competency framework.

### CODE REVIEW

**Comment by craigatproperly** [comment]
I haven't written this out or had the discussion of mapping to job titles this specifically before. Feedback @gavinsharp , @rsiu , @sktse

**Comment by craigatproperly** [comment]
(note you will want to view the rich text diff)

**Comment by sktse** [comment]
We have cultural and technical competencies.  Would those percentages apply to both of those combined or only Technical? 

If only Technical, how do we accommodate for cultural ones?
If both, we could get promotions skewing to the cultural side and not actually on technical ability.

**Comment by rsiu** [comment]
I like the proposal, assuming the general Properly competencies are included in the percentages.  Re: @sktse’s comment, I’m not so concerned about promotions skewing to cultural vs technical because of the key competency requirements, which build off of each previous step (i.e. you would at minimum need to be proficient in all of "Tech Design, Implementation and Code Ownership”, “Communication”, and “System Design” for SW Dev III).  Also feel that the “other competencies” percentages supports having a more diverse team with different yet equally important strengths.

**Comment by craigatproperly** [comment]
Verbal discussion confirmed role of key metrics

**Pull request merged**
